apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
configMapGenerator:
  - name: jmeter-grafana
    files:
      - ds_influxdb.yaml
      - dashboard.yaml
      - grafana.ini
  - name: jmeter-dashboards
    files:
      - GrafanaJMeterTemplate.json
      - GrafanaJMeterTemplate2.json

generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  version: v8
nameSuffix: -v8
  
